// <auto-generated />
namespace MoviesDatabase.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Allowmoviewithoutbook : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Allowmoviewithoutbook));
        
        string IMigrationMetadata.Id
        {
            get { return "201706042338253_Allow movie without book"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
